---
- name: Check if dotfiles repo exists
  stat:
    path: "{{ ansible_env.HOME }}/.dotfiles"
  register: dotfiles_stat

- name: Check if gear repo exists
  stat:
    path: "{{ ansible_env.HOME }}/.gear"
  register: gear_stat

- name: Check if amun script exists
  stat:
    path: "{{ ansible_env.HOME }}/bin/amun"
  register: amun_stat

- name: Update and upgrade packages (Debian)
  apt:
    upgrade: full
    update_cache: yes
    allow_downgrade: yes
    autoclean: yes
    autoremove: yes
  become: true
  retries: 5
  delay: 5
  register: result
  until: result is not failed
  when: ansible_facts['os_family'] == 'Debian'

- name: Update and upgrade Homebrew formulae (macOS)
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  when: ansible_facts['os_family'] == 'Darwin'

- name: Update and upgrade Homebrew casks (macOS)
  community.general.homebrew_cask:
    upgrade_all: true
    greedy: true
  when: ansible_facts['os_family'] == 'Darwin'

- name: Cleanup Homebrew cache (macOS)
  command: brew cleanup
  changed_when: false
  when: ansible_facts['os_family'] == 'Darwin'

- name: Update and upgrade packages (Arch)
  community.general.pacman:
    update_cache: yes
    upgrade: yes
  become: true
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Find orphan packages (Arch)
  command: pacman -Qdtq
  register: orphans
  changed_when: false
  failed_when: false
  become: true
  when: ansible_facts['os_family'] == 'Archlinux'

- name: Remove orphan packages (Arch)
  command: "pacman -Rns --noconfirm {{ orphans.stdout_lines | join(' ') }}"
  become: true
  when:
    - ansible_facts['os_family'] == 'Archlinux'
    - orphans.rc == 0
    - orphans.stdout_lines | length > 0

- name: Update dotfiles repo
  git:
    repo: "https://github.com/GonzaloAlvarez/dotfiles.git"
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    update: yes
  when: dotfiles_stat.stat.exists
  register: dotfiles_update

- name: Run dotfiles setup
  ansible.builtin.shell:
    cmd: "./setup"
    chdir: "{{ ansible_env.HOME }}/.dotfiles/"
  when:
    - dotfiles_stat.stat.exists
    - dotfiles_update is changed

- name: Update gear repo
  git:
    repo: "https://github.com/GonzaloAlvarez/gear.git"
    dest: "{{ ansible_env.HOME }}/.gear"
    update: yes
  when: gear_stat.stat.exists

- name: Update amun script
  get_url:
    url: https://raw.githubusercontent.com/gonzaloalvarez/amun/main/amun
    dest: "{{ ansible_env.HOME }}/bin/amun"
    mode: "0755"
  when: amun_stat.stat.exists
